osx_image: xcode7
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8

cache:
  - bundler
  - cocoapods

script:
  - bash -x test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
