osx_image: xcode7
language: objective-c
podfile: Podfile

env:
  global:
    - LANG=en_US.UTF-8

cache:
  - bundler
  - cocoapods

script:
  - bash -x test.sh

after_success:
  - find ~/Library/Developer/Xcode/DerivedData -name 'Coverage.profdata'
  - bash <(curl -s https://codecov.io/bash)
